config/routes.rb
Rails.application.routes.draw do

  get 'admin/orders'
  get 'admin' => 'admin#orders'
  get 'admin/locations'
  get 'admin/items'
  get 'admin/menus'
  get 'admin/users'
  get 'admin/categories'

  devise_for :users
  devise_scope :user do
    get '/admin/login' => 'devise/sessions#new'
    get '/admin/logout' => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, controller: "user"
  root 'order#new'

  resources :locations  do
    resources :menus, shallow: true
    resources :orders, shallow: true
  end

  get 'shouldRefresh' => "orders#has_recent_order"
  resources :orders do
    patch 'confirm', on: :member
  end

  resources :menus  do
    resources :sections, shallow: true
  end

  resources :sections  do
    resources :section_items, shallow: true
  end

  resources :categories do
    resources :category_sections, shallow: true
  end

  resources :category_sections do
    resources :category_options, shallow: true
  end

  get 'menus/:menu_id/items/:item_id', to: 'bag_items#new'

  resources :items
  resources :bags do
    resources :bag_items, shallow: true
  end

  resources :bag_items do
    resources :bag_item_choices, shallow: true
  end
  # resources :bags

  get 'order/locations/:location_id/menus', to: 'order#menus'
  get 'order/locations/:location_id/menus/:menu_id', to: 'order#menus'
  get 'order/new'
  get 'order' => 'order#new'
  get 'takeout' => 'order#new'
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :menu
  has_many :section_items, -> { order(:position) }, dependent: :destroy
  has_many :items, through: :section_items

  acts_as_list scope: :menu

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 499 }
  validates :position, numericality: { minimum: 1, only_integer: true }

  scope :sorted, -> { order("sections.position") }
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :menu, only: [:new, :create]
  load_and_authorize_resource :section, through: :menu, shallow: true

  layout 'admin'

  # GET /sections/new
  def new
    # @section = Section.new(menu_id: @menu.id)
    @sections_count = Section.where(menu_id: @menu.id).count + 1
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /sections/1/edit
  def edit
    @sections_count = Section.where(menu_id: @section.menu_id).count
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /sections
  # POST /sections.json
  def create
    respond_to do |format|
      if @section.save
        format.html { redirect_to menu_url(@section.menu_id), notice: 'Section was successfully created.' }
        format.js {
          @sections = Section.where(menu_id: @section.menu_id).order(:position)
          flash[:notice] = "Section was successfully updated."
          render :index
        }
      else
        format.html { render :new }
        format.js {
          @sections_count = Section.where(menu_id: @menu.id).count + 1
          render :new
        }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to menu_url(@section.menu_id), notice: 'Section was successfully updated.' }
        format.js {
          @sections = Section.where(menu_id: @section.menu_id).order(:position)
          flash[:notice] = "Section was successfully updated."
          render :index
        }
      else
        format.html { render :edit }
        format.js { @sections_count = Section.where(menu_id: @section.menu_id).count
          render :edit
        }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to menu_url(@section.menu_id), notice: 'Section was successfully destroyed.' }
      format.js {
        @sections = Section.where(menu_id: @section.menu_id).order(:position)
        flash[:notice] = "Section was successfully deleted."
        render :index
      }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:menu_id, :name, :description, :position)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section, url: url, remote: remote) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %> (Optional)<br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.select :position, 1..@sections_count, {}, { class: "form-control" } %>
  </div>

  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/sections/_index.html.erb
<% count = 0 %>
<% sections.each do |section| %>
  <div class="panel panel-default">
      <div class="panel-heading">
          <h4 class="panel-title">
              <a data-toggle="collapse" href="#section<%= section.id %>">
                <%= section.name %>
                <%= link_to edit_section_path(section), remote: true do %>
                  <i class="fa fa-fw fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit this Section in the Menu"></i>
                <% end %>
                <%= link_to section, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                  <i class="fa fa-fw fa-trash-o" data-toggle="tooltip" data-placement="top" title="Remove this Section from the Menu"></i>
                <% end %>
                <%= link_to new_section_section_item_path(section), remote: true do %>
                  <i class="fa fa-fw fa-plus-square" data-toggle="tooltip" data-placement="top" title="Add Item in this Section of the Menu"></i>
                <% end %>
              </a>
          </h4>
      </div>
      <!-- .panel-heading -->
      <div id="section<%= section.id %>" class="panel-collapse collapse <%= count == 0 ? 'in' : '' %>">
        <div class="panel-body">
          <p class="lead"><%= section.description %></p>
          <div id="section_items<%= section.id %>" class="row">
            <%= render 'section_items/index', section_items: section.section_items %>
          </div>
          <!-- /.col-sm-4 -->
        </div>
      </div>
      <!-- .panel-collapse -->

  </div>
  <!-- .panel-default -->
  <% count += 1 %>
<% end %>

app/views/sections/edit.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: section_path(@section.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Edit this Section of the Menu");

app/views/sections/index.js.erb
$('#sections<%= @section.menu_id %>').html("<%= escape_javascript(render 'index', sections: @sections) %>");
$('#modalForm').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
initTooltip();

app/views/sections/new.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: menu_sections_path(@menu.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Create a New Section to the Menu");