config/routes.rb
Rails.application.routes.draw do

  get 'admin/orders'
  get 'admin' => 'admin#orders'
  get 'admin/locations'
  get 'admin/items'
  get 'admin/menus'
  get 'admin/users'
  get 'admin/categories'

  devise_for :users
  devise_scope :user do
    get '/admin/login' => 'devise/sessions#new'
    get '/admin/logout' => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, controller: "user"
  root 'order#new'

  resources :locations  do
    resources :menus, shallow: true
    resources :orders, shallow: true
  end

  get 'shouldRefresh' => "orders#has_recent_order"
  resources :orders do
    patch 'confirm', on: :member
  end

  resources :menus  do
    resources :sections, shallow: true
  end

  resources :sections  do
    resources :section_items, shallow: true
  end

  resources :categories do
    resources :category_sections, shallow: true
  end

  resources :category_sections do
    resources :category_options, shallow: true
  end

  get 'menus/:menu_id/items/:item_id', to: 'bag_items#new'

  resources :items
  resources :bags do
    resources :bag_items, shallow: true
  end

  resources :bag_items do
    resources :bag_item_choices, shallow: true
  end
  # resources :bags

  get 'order/locations/:location_id/menus', to: 'order#menus'
  get 'order/locations/:location_id/menus/:menu_id', to: 'order#menus'
  get 'order/new'
  get 'order' => 'order#new'
  get 'takeout' => 'order#new'
end

app/models/category_option.rb
class CategoryOption < ApplicationRecord
  belongs_to :category_section
  has_many :bag_item_choices
  has_many :bag_items, through: :bag_item_choices

  acts_as_list scope: :category_section

  validates :name, presence: true, length: { maximum: 80 }
  validates :price, presence: true, numericality: { minimum: 0 }
  validates :position, numericality: { minimum: 1, only_integer: true }

  def option
    price > 0 ? "#{self.name} +$#{price}" : self.name
  end
end

app/controllers/category_options_controller.rb
class CategoryOptionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :category_section, only: [:new, :create]
  load_and_authorize_resource :category_option, through: :category_section, shallow: true

  layout 'admin'

  # GET /category_sections/1/category_options/new
  def new
    @category_options_count = CategoryOption.where(category_section_id: @category_section.id).count + 1
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /category_options/1/edit
  def edit
    @category_options_count = CategoryOption.where(category_section_id: @category_option.category_section_id).count
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /category_sections/1/category_options
  # POST /category_sections/1/category_options.json
  def create
    respond_to do |format|
      if @category_option.save
        format.html { redirect_to category_url(@category_section.category_id),
          notice: 'Category option was successfully created.' }
        format.js  {
          @category_options = CategoryOption.where(category_section_id: @category_option.category_section_id).order(:position)
          flash[:notice] = "Option choice for the category was successfully created."
          render :index
        }
      else
        @category_options_count = CategoryOption.where(category_section_id: @category_section.id).count + 1
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /category_options/1
  # PATCH/PUT /category_options/1.json
  def update
    respond_to do |format|
      if @category_option.update(category_option_params)
        format.html { redirect_to @category_option, notice: 'Category option was successfully updated.' }
        format.js  {
          @category_options = CategoryOption.where(category_section_id: @category_option.category_section_id).order(:position)
          flash[:notice] = "Option choice for the category was successfully updated."
          render :index
        }
      else
        @category_options_count = CategoryOption.where(category_section_id: @category_option.category_section_id).count
        format.html { render :edit }
        format.js { render :edit }
      end
    end
  end

  # DELETE /category_options/1
  # DELETE /category_options/1.json
  def destroy
    @category_option.destroy
    respond_to do |format|
      format.html { redirect_to category_options_url, notice: 'Category option was successfully destroyed.' }
      format.js {
        @category_options = CategoryOption.where(category_section_id: @category_option.category_section_id).order(:position)
        flash[:notice] = "Option choice for the category was successfully deleted."
        render :index
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_option
      @category_option = CategoryOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_option_params
      params.require(:category_option).permit(:name, :price, :position, :category_section_id)
    end

    def set_category_section
      @category_section = categorySection.find(params[:category_section_id]) if params[:category_section_id]
    end
end

app/helpers/category_options_helper.rb
module CategoryOptionsHelper
end

app/views/category_options/_form.html.erb
<%= form_for(@category_option, url: url, remote: remote) do |f| %>
  <% if @category_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_option.errors.count, "error") %> prohibited this Category Option Choice from being saved:</h2>

      <ul>
      <% @category_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.select :position, 1..@category_options_count, {}, { class: "form-control" } %>
  </div>

  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/category_options/_index.html.erb
<% category_options.each do |category_option| %>

<dt><%= number_to_currency(category_option.price, precision: 2) %></dt>
<dd>
  <%= category_option.name %>
  <%= link_to edit_category_option_path(category_option.id), remote: true do %>
    <i class="fa fa-fw fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit this Category Option Choice"></i>
  <% end %>
  <%= link_to category_option, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
    <i class="fa fa-fw fa-trash-o" data-toggle="tooltip" data-placement="top" title="Delete this Category Option Choice"></i>
  <% end %>
</dd>
<% end %>

app/views/category_options/edit.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: category_option_path(@category_option.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Edit Category Option Choice");

app/views/category_options/index.js.erb
$('#categorySection<%= @category_option.category_section_id %>').html("<%= escape_javascript(render 'index', category_options: @category_options) %>");
$('#modalForm').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
initTooltip();

app/views/category_options/new.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: category_section_category_options_path(@category_option.category_section_id),remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Add Category Option Choice");