config/routes.rb
Rails.application.routes.draw do

  get 'admin/orders'
  get 'admin' => 'admin#orders'
  get 'admin/locations'
  get 'admin/items'
  get 'admin/menus'
  get 'admin/users'
  get 'admin/categories'

  devise_for :users
  devise_scope :user do
    get '/admin/login' => 'devise/sessions#new'
    get '/admin/logout' => 'devise/sessions#destroy'
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, controller: "user"
  root 'order#new'

  resources :locations  do
    resources :menus, shallow: true
    resources :orders, shallow: true
  end

  get 'shouldRefresh' => "orders#has_recent_order"
  resources :orders do
    patch 'confirm', on: :member
  end

  resources :menus  do
    resources :sections, shallow: true
  end

  resources :sections  do
    resources :section_items, shallow: true
  end

  resources :categories do
    resources :category_sections, shallow: true
  end

  resources :category_sections do
    resources :category_options, shallow: true
  end

  get 'menus/:menu_id/items/:item_id', to: 'bag_items#new'

  resources :items
  resources :bags do
    resources :bag_items, shallow: true
  end

  resources :bag_items do
    resources :bag_item_choices, shallow: true
  end
  # resources :bags

  get 'order/locations/:location_id/menus', to: 'order#menus'
  get 'order/locations/:location_id/menus/:menu_id', to: 'order#menus'
  get 'order/new'
  get 'order' => 'order#new'
  get 'takeout' => 'order#new'
end

app/models/section_item.rb
class SectionItem < ApplicationRecord
  belongs_to :section
  belongs_to :item

  acts_as_list scope: :section

  validates :position, numericality: { minimum: 1, only_integer: true }

  scope :sorted, -> { order("section_items.position") }
end

app/controllers/section_items_controller.rb
class SectionItemsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :section, only: [:new, :create]
  load_and_authorize_resource :section_item, through: :section, shallow: true

  layout 'admin'

  # GET /section_items/new
  def new
    @items = Item.where.not(id: SectionItem.select(:item_id).
    where(section_id: @section.id)).sorted
    @section_items_count = SectionItem.where(section_id: @section.id).count + 1
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /section_items/1/edit
  def edit
    @items = Item.where.not(id: SectionItem.select(:item_id).
    where(section_id: @section_item.section_id).
    where.not(item_id: @section_item.item_id)).sorted
    @section_items_count = SectionItem.where(section_id: @section_item.section_id).count
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /section_items
  # POST /section_items.json
  def create
    respond_to do |format|
      if @section_item.save
        format.html { redirect_to menu_url(@section.menu_id),
          notice: 'The item was added successfully to the Menu.' }
        format.js {
          @section_items = SectionItem.where(section_id: @section_item.section_id).order(:position)
          flash[:notice] = "Section item was successfully created."
          render :index
        }
      else
        format.html { render :new }
        format.js {
          @items = Item.where.not(id: SectionItem.select(:item_id).
          where(section_id: @section.id)).sorted
          @section_items_count = SectionItem.where(section_id: @section.id).count + 1
          render :new
        }
      end
    end
  end

  # PATCH/PUT /section_items/1
  # PATCH/PUT /section_items/1.json
  def update
    respond_to do |format|
      if @section_item.update(section_item_params)
        format.html { redirect_to menu_url(@section_item.section.menu_id),
          notice: 'Section item was successfully updated.' }
        format.js {
          @section_items = SectionItem.where(section_id: @section_item.section_id).order(:position)
          flash[:notice] = "Section item was successfully updated."
          render :index
        }
      else
        format.html { render :edit }
        format.js {
          @items = Item.where.not(id: SectionItem.select(:item_id).
          where(section_id: @section_item.section_id).
          where.not(item_id: @section_item.item_id)).sorted
          @section_items_count = SectionItem.where(section_id: @section_item.section_id).count
          render :edit
        }
      end
    end
  end

  # DELETE /section_items/1
  # DELETE /section_items/1.json
  def destroy
    @section_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_url(@section_item.section.menu_id), notice: 'Location was successfully destroyed.' }
      format.js {
        @section_items = SectionItem.where(section_id: @section_item.section_id).order(:position)
        flash[:notice] = "Section item was successfully deleted."
        render :index
      }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_item_params
      params.require(:section_item).permit(:section_id, :item_id, :position)
    end
end

app/helpers/section_items_helper.rb
module SectionItemsHelper
end

app/views/section_items/_form.html.erb
<%= form_for(@section_item, url: url, remote: remote) do |f| %>
  <% if @section_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section_item.errors.count, "error") %> prohibited this menu item from being saved:</h2>

      <ul>
      <% @section_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :item %>
    <%= f.collection_select :item_id, @items, :id, :display, {}, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.select :position, 1..@section_items_count, {}, {class: "form-control"} %>
  </div>

  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/section_items/_index.html.erb
<% section_items.each do |section_item| %>
<% item = section_item.item %>
<div class="col-sm-6 col-lg-4 col-md-4">
    <div class="thumbnail">
        <div class="caption">
            <h4 class="pull-right"><%= number_to_currency(item.price, precision: 2) %></h4>
            <h4>
              <%= item.display %>
              <%= link_to section_item, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                <i class="fa fa-fw fa-trash-o" data-toggle="tooltip" data-placement="top" title="Remove Item in this Section of the Menu"></i>
              <% end %>
              <%= link_to edit_section_item_path(section_item.id), remote: true do %>
                <i class="fa fa-fw fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit Item in this Section of the Menu"></i>
              <% end %>
            </h4>
            <p><%= item.description %></p>
        </div>
    </div>
</div>
<% end %>

app/views/section_items/edit.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: section_item_path(@section_item.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Edit Item in this Section of the Menu");

app/views/section_items/index.js.erb
$('#section_items<%= @section_item.section_id %>').html("<%= escape_javascript(render 'index', section_items: @section_items) %>");
$('#modalForm').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

app/views/section_items/new.html.erb
<h1>Adding an Item to the Menu in the <%= @section.name %> section.</h1>

<%= form_for(@section_item, url: section_section_items_path(@section.id), method: :post) do |f| %>
  <%= render 'form', section_item: @section_item, f: f %>
<% end %>

<%= link_to 'Back', menu_path(@section.menu_id) %>

app/views/section_items/new.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: section_section_items_path(@section.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Add New Item in this Section of the Menu");